apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: production
  labels:
    app: orders-api

spec:
  type: LoadBalancer

  selector:
    app: orders-api

  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: orders-api
  namespace: production

spec:
  replicas: 2

  selector:
    matchLabels:
      app: orders-api

  template:
    metadata:
      labels:
        app: orders-api

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"

    spec:
      containers:

        - name: orders-api

          image: 771650096212.dkr.ecr.eu-central-1.amazonaws.com/production-devsecops-platform-dev-api:4847ef2f4d1bbeeb6efbfca9b529291a1f12b165

          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          envFrom:

            - configMapRef:
                name: app-config

            - secretRef:
                name: app-secret

          startupProbe:
            httpGet:
              path: /health
              port: 8000

            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: 8000

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 20
            periodSeconds: 15

          resources:

            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi