apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  SERVICE_NAME: orders-api

  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"

  REDIS_HOST: redis
  REDIS_PORT: "6379"

  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"

  LOG_LEVEL: INFO