apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storageclass.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - api.yaml
  - worker.yaml